name: flutter_application_lab_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  firebase_auth: ^4.4.0
  sqflite: ^2.3.3
  cloud_firestore: ^4.8.2
  firebase_messaging: ^14.7.0
  test: ^1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
