// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFYmpKVa22RO-vszz5GlqQzzyr8HHwnc',
    appId: '1:251888664972:web:e26ec2f91281f5c749d6a9',
    messagingSenderId: '251888664972',
    projectId: 'lab-10-1-c3cc0',
    authDomain: 'lab-10-1-c3cc0.firebaseapp.com',
    storageBucket: 'lab-10-1-c3cc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7uYAOlaeqMjWvxmkLTia8LEl1BChgf0',
    appId: '1:251888664972:android:d39a929a960db57749d6a9',
    messagingSenderId: '251888664972',
    projectId: 'lab-10-1-c3cc0',
    storageBucket: 'lab-10-1-c3cc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1Mh09K_vcgKGRg93I2ehFGmJJtHuuUc',
    appId: '1:251888664972:ios:52047e2c95100e3749d6a9',
    messagingSenderId: '251888664972',
    projectId: 'lab-10-1-c3cc0',
    storageBucket: 'lab-10-1-c3cc0.appspot.com',
    iosBundleId: 'com.example.flutterApplicationLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI1Mh09K_vcgKGRg93I2ehFGmJJtHuuUc',
    appId: '1:251888664972:ios:52047e2c95100e3749d6a9',
    messagingSenderId: '251888664972',
    projectId: 'lab-10-1-c3cc0',
    storageBucket: 'lab-10-1-c3cc0.appspot.com',
    iosBundleId: 'com.example.flutterApplicationLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFYmpKVa22RO-vszz5GlqQzzyr8HHwnc',
    appId: '1:251888664972:web:1426cf63cd78e62d49d6a9',
    messagingSenderId: '251888664972',
    projectId: 'lab-10-1-c3cc0',
    authDomain: 'lab-10-1-c3cc0.firebaseapp.com',
    storageBucket: 'lab-10-1-c3cc0.appspot.com',
  );
}
